### ISSUE TITLE
not ready for CheckMK 2

### ISSUE THREAD

**Issue by righter83** [modusoft/lm-sensors#1]
Hi
when I use it on the new beta I got this error:

`Failed to auto-migrate legacy plugin to check plugin: lmsensors.fan
Please refer to Werk 10601 for more information.
Failed to auto-migrate legacy plugin to check plugin: lmsensors.temp
Please refer to Werk 10601 for more information.
Failed to auto-migrate legacy plugin to check plugin: lmsensors.volt
Please refer to Werk 10601 for more information.
`

**Comment by cboseck** [comment]
Yes, the plugin api changed in CheckMK 2.
As far as I know, is going to need a rewrite.

**Comment by cboseck** [comment]
This is the new version of the plugin for checkmk 2.
https://github.com/modusoft/lmsensors2
